# Generated by Django 3.1.6 on 2021-02-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
    ]
