# Generated by Django 3.1.6 on 2021-02-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210219_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vote',
            new_name='score',
        ),
    ]
