# Generated by Django 3.1.6 on 2021-02-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210221_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.TextField(default='this is the header'),
            preserve_default=False,
        ),
    ]
