# Generated by Django 3.1.6 on 2021-02-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210222_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='heading',
            new_name='header',
        ),
    ]
