# Generated by Django 3.1.6 on 2021-02-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
